name: Send tweets

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  post-tweets:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_GITHUB }}
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e 'install.packages(c("rtweet","dplyr","glue","stringr","rvest","git2r","lubridate","magick","webshot"), dependencies = TRUE)'
      - name: Create and post tweet
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
          HOCKEYR_TWITTER_CONSUMER_API_KEY: ${{ secrets.HOCKEYR_TWITTER_CONSUMER_API_KEY }}
          HOCKEYR_TWITTER_CONSUMER_API_SECRET: ${{ secrets.HOCKEYR_TWITTER_CONSUMER_API_SECRET }}
          HOCKEYR_TWITTER_ACCESS_TOKEN: ${{ secrets.HOCKEYR_TWITTER_ACCESS_TOKEN }}
          HOCKEYR_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.HOCKEYR_TWITTER_ACCESS_TOKEN_SECRET }}
        run: Rscript post_hockeyR_tweets.R
      - name: Updating last commit
        run: |
          git config --global user.name "hockeyR-github-actions[bot]"
          git config --global user.email "hockeyR-github-actions@users.noreply.github.com"
          git commit -a -m "Add latest hockeyR commit"
          git push origin